// angular/demo/src/app/demo/settings/settings.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss']
})
export class SettingsComponent {
}

<app-title></app-title>
<div class="panelCard">
    <mat-accordion [multi]="true">
        <mat-expansion-panel>
            <mat-expansion-panel-header>
                <mat-panel-title>
                    Turn on notifications
                </mat-panel-title>
            </mat-expansion-panel-header>
            <div class="inline">
                <h4 class="mat-subheading-2">Turn on device alarm notifications</h4>
                <mat-slide-toggle color="primary"></mat-slide-toggle>
            </div>
        </mat-expansion-panel>

        <mat-expansion-panel>
            <mat-expansion-panel-header>
                <mat-panel-title>
                    Hide low priority alarms
                </mat-panel-title>
            </mat-expansion-panel-header>
            <div class="inline">
                <h4>Hide all low priority device alarm notifications</h4>
                <mat-checkbox></mat-checkbox>
            </div>
        </mat-expansion-panel>

        <mat-expansion-panel>
            <mat-expansion-panel-header>
                <mat-panel-title>
                    Set screen brightness
                </mat-panel-title>
            </mat-expansion-panel-header>
            <mat-slider thumbLabel min="1" max="100" value="50" style="width: 100%;"></mat-slider>
        </mat-expansion-panel>

        <mat-expansion-panel>
            <mat-expansion-panel-header>
                <mat-panel-title>
                    Set display density
                </mat-panel-title>
            </mat-expansion-panel-header>
            <mat-chip-list style="padding: 20px;">
                <mat-chip color="primary" selected>Default</mat-chip>
                <mat-chip>Comfortable</mat-chip>
                <mat-chip>Compact</mat-chip>
            </mat-chip-list>
        </mat-expansion-panel>
    </mat-accordion>
</div>

// react/demo/src/pages/settings.js
import React from 'react';
import { withStyles } from '@material-ui/core/styles';

import Checkbox from '@material-ui/core/Checkbox';
import Chip from '@material-ui/core/Chip';
import ExpandMoreIcon from '@material-ui/icons/ExpandMore';
import ExpansionPanel from '@material-ui/core/ExpansionPanel';
import ExpansionPanelDetails from '@material-ui/core/ExpansionPanelDetails';
import ExpansionPanelSummary from '@material-ui/core/ExpansionPanelSummary';
import Slider from '@material-ui/core/Slider';
import Switch from '@material-ui/core/Switch';
import Typography from '@material-ui/core/Typography';

const styles = (theme) => ({
    secondaryHeading: {
        color: theme.palette.text.secondary,
        flex: 1,
    },
    chip: {
        margin: '5px',
    },
    panelCard: {
        paddingTop: '16px',
        margin: 'auto',
        width: '90%',
        maxWidth: '800px',
    },
});

class Settings extends React.Component {
    render() {
        const { classes } = this.props;
        return (
            <div className={classes.panelCard}>
                <ExpansionPanel>
                    <ExpansionPanelSummary expandIcon={<ExpandMoreIcon />}>
                        <Typography variant="subtitle2" color="inherit">
                            {' '}
                            Turn on notifications{' '}
                        </Typography>
                    </ExpansionPanelSummary>
                    <ExpansionPanelDetails style={{ alignItems: 'center' }}>
                        <Typography className={classes.secondaryHeading} variant="subtitle2">
                            Turn on device alarm notifications
                        </Typography>
                        <Switch color="primary" />
                    </ExpansionPanelDetails>
                </ExpansionPanel>
                <ExpansionPanel>
                    <ExpansionPanelSummary expandIcon={<ExpandMoreIcon />}>
                        <Typography variant="subtitle2" color="inherit">
                            Hide low priority alarms
                        </Typography>
                    </ExpansionPanelSummary>
                    <ExpansionPanelDetails style={{ alignItems: 'center' }}>
                        <Typography className={classes.secondaryHeading} variant="subtitle2">
                            Hide all low priority device alarm notifications
                        </Typography>
                        <Checkbox />
                    </ExpansionPanelDetails>
                </ExpansionPanel>
                <ExpansionPanel>
                    <ExpansionPanelSummary expandIcon={<ExpandMoreIcon />}>
                        <Typography variant="subtitle2" color="inherit">
                            Set screen brightness
                        </Typography>
                    </ExpansionPanelSummary>
                    <ExpansionPanelDetails style={{ paddingRight: '15px' }}>
                        <Slider defaultValue={50} min={0} max={100} valueLabelDisplay="auto" />
                    </ExpansionPanelDetails>
                </ExpansionPanel>
                <ExpansionPanel>
                    <ExpansionPanelSummary expandIcon={<ExpandMoreIcon />}>
                        <Typography variant="subtitle2" color="inherit">
                            Set display density
                        </Typography>
                    </ExpansionPanelSummary>
                    <ExpansionPanelDetails style={{ padding: '20px' }}>
                        <Chip clickable size="small" label="Default" color="primary" className={classes.chip} />
                        <Chip clickable size="small" label="Comfortable" className={classes.chip} />
                        <Chip clickable size="small" label="Compact" className={classes.chip} />
                    </ExpansionPanelDetails>
                </ExpansionPanel>
            </div>
        );
    }
}
export default withStyles(styles)(Settings);
